### Create Contact (Success Example)
POST http://localhost:8080/api/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RpbmciLCJuYW1lIjoiU2FuZGkgMTIzIiwiZXhwIjoxNzUyODgzMTc1fQ.1VlQMFQh9xP0X23ba-8MVuKwcyDeZyOljaBwLVYqtww
Content-Type: application/json

{
  "first_name": "fachran 3",
  "last_name": "sandi 2",
  "email": "coba@gmail.com",
  "phone": "32423423434"
}

### Create Contact (Invalid Email Example)
POST http://localhost:8080/api/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RpbmciLCJuYW1lIjoidGVzdGluZyIsImV4cCI6MTc1MjYzNjc1NH0.pPa-fYh1FDoea028R0yZLhnKZRJgi3vwyOHOBwXFuho
Content-Type: application/json

{
  "first_name": "fachran",
  "last_name": "sandi",
  "email": "not-valid-email",
  "phone": "32423423434"
}

### Create Contact (Missing Field Example)
POST http://localhost:8080/api/contacts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RpbmciLCJuYW1lIjoidGVzdGluZyIsImV4cCI6MTc1MjYzNjc1NH0.pPa-fYh1FDoea028R0yZLhnKZRJgi3vwyOHOBwXFuho
Content-Type: application/json

{
  "first_name": "",
  "last_name": "sandi",
  "email": "test@test.com",
  "phone": "32423423434"
}
