### Get Contact
GET http://localhost:8080/api/contacts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJ0ZXN0aW5nIiwibmFtZSI6IlNhbmRpIiwiZXhwIjoxNzUyNTY5NjM4fQ.20Mg64fgX3_ElPx093jx-YM2Wf2X1xfoaqpLBLGr8UI