### Search Contacts
GET http://localhost:8080/api/contacts?page=1&size=5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJ0ZXN0aW5nIiwibmFtZSI6IlNhbmRpIiwiZXhwIjoxNzUwOTk4OTg3fQ.Fij7RIuvZ_gBsPM2RLo4bMcRzxtq1WqkB5L7tgymsDk


### Search Contacts
GET http://localhost:8080/api/contacts?name=sandi&page=1&size=5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMCwidXNlcm5hbWUiOiJ0ZXN0aW5nIiwibmFtZSI6IlNhbmRpIiwiZXhwIjoxNzUwOTk4OTg3fQ.Fij7RIuvZ_gBsPM2RLo4bMcRzxtq1WqkB5L7tgymsDk
