### Search Contacts
GET http://localhost:8080/api/contacts?page=1&size=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RpbmciLCJuYW1lIjoiVGVzdGluZyBTYW5kaSIsImV4cCI6MTc1Mjc2MDM1Mn0.dUkuq_RHaTB4tGvrMIxjVOZCwideuwSXZLf8ir9Dilc


### Search Contacts
GET http://localhost:8080/api/contacts?name=sandi&page=1&size=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InRlc3RpbmciLCJuYW1lIjoiVGVzdGluZyBTYW5kaSIsImV4cCI6MTc1Mjc2MDM1Mn0.dUkuq_RHaTB4tGvrMIxjVOZCwideuwSXZLf8ir9Dilc
